[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm install --omit=dev',
  'cd client && npm install'
]

[phases.build]
cmds = [
  'cd client && GENERATE_SOURCEMAP=false npm run build'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
CI = 'false'
GENERATE_SOURCEMAP = 'false'
NODE_OPTIONS = '--max_old_space_size=1024' 