[variables]
NODE_ENV = 'production'
CI = 'false'
GENERATE_SOURCEMAP = 'false'

[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm install --omit=dev'
]

[phases.build]
cmds = [
  'cd client && npm run build'
]

[start]
cmd = 'npm start' 