[variables]
NODE_ENV = 'production'
CI = 'false'
GENERATE_SOURCEMAP = 'false'

[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm install --omit=dev'
]

[phases.build]
cmds = [
  'echo "Ensuring build files are in correct location..."',
  'if [ -d "build" ] && [ ! -d "client/build" ]; then cp -r build client/build; fi',
  'ls -la client/ || echo "client directory check"'
]

[start]
cmd = 'npm start' 